User.create!({username: "lew", password: "asdfasdf", admin: true})
User.create!({username: "guest", password: "password1", admin: false})

Expense.create!({user_id:1, amount:43, description:"gas"})
Expense.create!({user_id:1, amount:800, description:"rent"})
Expense.create!({user_id:2, amount:900, description:"rent"})
Expense.create!({user_id:2, amount:151, description:"utilities"})
Expense.create!({user_id:1, amount:13, description:"dinner"})
Expense.create!({user_id:1, amount:7.56, description:"lunch"})
Expense.create!({user_id:1, amount:23.98, description:"birthday gift for Jill"})
Expense.create!({user_id:2, amount:34.65, description:"gas"})
Expense.create!({user_id:2, amount:20.32, description:"gas"})
Expense.create!({user_id:2, amount:22.86, description:"groceries"})
Expense.create!({user_id:2, amount:15.43, description:"dinner"})
Expense.create!({user_id:1, amount:35.60, description:"groceries"})
Expense.create!({user_id:2, amount:6.75, description:"lunch"})
Expense.create!({user_id:1, amount:17.76, description:"gas"})
